### ISSUE TITLE
detection of Uplink-type

### ISSUE THREAD

**Issue by SvenRoederer** [Akira25/autoupdate#3]
Your detection of uplink-type should not rely on the logic you are using in https://github.com/Akira25/autoupdate/blob/7da9afa1a90a5f378a2af2a897dc189ef202d2d7/autoupdate#L36 the more relying solution should check the uci-setting ffberlin-uplink.preset.current

**Comment by akira25** [comment]
Solved with PR #4. The script now uses uci setting *ffberlin-uplink.preset.current*
